# Generated by Django 3.2.6 on 2021-08-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='creat_timestamp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delete_timestamp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='update_timestamp',
        ),
    ]
