# Generated by Django 3.2.6 on 2021-08-11 08:00

import customer.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_address_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[customer.validations.phone_validation], verbose_name='Phone'),
        ),
    ]
