# Generated by Django 3.2.6 on 2021-08-03 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('creat_time', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 13, 7, 2, 632895))),
                ('name', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('n', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('creat_time', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 13, 7, 2, 632895))),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('creat_time', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 13, 7, 2, 632895))),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('creat_time', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 13, 7, 2, 632895))),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('price', models.IntegerField(null=True, verbose_name='Price')),
                ('view', models.IntegerField(default=0, verbose_name='View')),
                ('sale', models.IntegerField(default=0, verbose_name='Sale')),
                ('material', models.CharField(max_length=50, null=True, verbose_name='Material')),
                ('features', models.CharField(max_length=500, null=True, verbose_name='Features')),
                ('specialized_features', models.CharField(max_length=500, null=True, verbose_name='Specialized Features')),
                ('score', models.FloatField(default=0, verbose_name='Score')),
                ('short_detail', models.CharField(max_length=500, verbose_name='Short Detail')),
                ('detail', models.CharField(max_length=2000, verbose_name='Detail')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='Brand Name')),
                ('child_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.childcategory', verbose_name='Child Category')),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.parentcategory', verbose_name='Parent Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('creat_time', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 13, 7, 2, 632895))),
                ('size', models.IntegerField(verbose_name='Size')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('creat_time', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 13, 7, 2, 632895))),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='childcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.parentcategory', verbose_name='Parent'),
        ),
    ]
