# Generated by Django 3.2.6 on 2021-08-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='category/icon/default.png', upload_to='category/icon', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/image/default.svg', upload_to='category/image', verbose_name='Image'),
        ),
    ]
