# Generated by Django 3.2.6 on 2021-08-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210804_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(default='category/icon/default.png', upload_to='category/icon', verbose_name='Icon'),
        ),
    ]
