# Generated by Django 3.2.6 on 2021-08-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='category/icon/default.png', upload_to='category/icon', verbose_name='Icon'),
        ),
    ]
