# Generated by Django 3.2.6 on 2021-08-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/image/default.jpeg', upload_to='category/image', verbose_name='Image'),
        ),
    ]
