# Generated by Django 3.2.6 on 2021-08-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productimage'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/image/default.jpg', upload_to='category/image', verbose_name='Image'),
        ),
    ]
