# Generated by Django 3.2.6 on 2021-08-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210804_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='/product/default.jpg', upload_to='product', verbose_name='Image'),
        ),
    ]
