# Generated by Django 3.2.6 on 2021-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='Total Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CA', 'Canceled'), ('PE', 'Pending'), ('CO', 'Completed')], max_length=20, verbose_name='Status'),
        ),
    ]
