# Generated by Django 3.2.6 on 2021-08-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_size_product'),
        ('order', '0005_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='Size'),
            preserve_default=False,
        ),
    ]
